name: "NFR Badge"
description: "Update readme.md with NFR badgets"
inputs:
  readme-fname:
    description: "readme file"
    default: "README.md"
    required: true
  nfr-fnames:
    description: "nfr files separated by space"
    required: true
runs:
  using: "composite"
  steps:
      - shell: sh
        run: echo ${{ inputs.readme-fname }}
      - shell: sh
        run: echo ${{ inputs.nfr-fnames }}
      - shell: sh
        run: echo ${{ github.action_path }}/nfr_badge/nfr_badge.sh --readme ${{ inputs.readme-fname }} ${{ inputs.nfr-fnames }}
      - shell: sh
        run: ${{ github.action_path }}/nfr_badge/nfr_badge.sh --readme ${{ inputs.readme-fname }} ${{ inputs.nfr-fnames }}
