name: "NFR Badge"
description: "Update readme.md with NFR badgets"
inputs:
  nfr-fnames:
    description: "nfr files separated by space"
    required: true
runs:
  using: "composite"
  steps:
      - shell: sh
        run: ${{ github.action_path }}/nfr_badge/nfr_badge.sh ${{ inputs.nfr-fnames }}
